### ISSUE TITLE
gff3_fix - problem with split function

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/GFF3toolkit#103]
I got the following error with gff3_fix:

```
Traceback (most recent call last):
  File "/app/data/mpoelchau/python3_venv/bin/gff3_fix", line 9, in <module>
    load_entry_point('gff3tool==2.0.1', 'console_scripts', 'gff3_fix')()
  File "/app/data/mpoelchau/GFF3toolkit/gff3tool/bin/gff3_fix.py", line 95, in script_main
    gff3_fix.fix.main(gff3=gff3, output_gff=args.output_gff, error_dict=error_dict, line_num_dict=line_num_dict, logger=logger_null)
  File "/app/data/mpoelchau/GFF3toolkit/gff3tool/lib/gff3_fix/fix.py", line 689, in main
    split(gff3=gff3, error_list=error_dict[error_code], logger=logger)
  File "/app/data/mpoelchau/GFF3toolkit/gff3tool/lib/gff3_fix/fix.py", line 180, in split
    childgroup = connected_compoents(childrenlist, hitpair)
  File "/app/data/mpoelchau/GFF3toolkit/gff3tool/lib/gff3_fix/fix.py", line 275, in connected_compoents
    for v in nodelist.itervalues():
AttributeError: 'dict' object has no attribute 'itervalues'
```

It looks like the problem is with the `connected_compoents` function, which is used by the `split` function. This function is not currently tested with our test files.

**Comment by mpoelchau** [comment]
Fixed in  commit 200fdb9. Thanks @ShangYuChiang!
