### ISSUE TITLE
FileNotFoundError: No such file or directory: 'makeblastdb' while running gff3_QC

### ISSUE THREAD

**Issue by hj-99** [NAL-i5K/GFF3toolkit#139]
Hello, thank you for developing this useful tool! I encountered an error while running gff3_QC and need some help troubleshooting.

I used the following command:
gff3_QC -g my.gff3 -f my.fa -o report.txt -s statistic.txt

I received the following error message:
Traceback (most recent call last):
  File "/public1/home/sc30852/anaconda3/envs/GFF_env/bin/gff3_QC", line 33, in <module>
    sys.exit(load_entry_point('gff3tool==2.1.0', 'console_scripts', 'gff3_QC')())
  File "/public1/home/sc30852/anaconda3/envs/GFF_env/lib/python3.8/site-packages/gff3tool-2.1.0-py3.8.egg/gff3tool/bin/gff3_QC.py", line 103, in script_main
    cmd = inter_model.main(gff3, args.gff, args.fasta, logger=logger_stderr, noncanonical_gene=args.noncanonical_gene)
  File "/public1/home/sc30852/anaconda3/envs/GFF_env/lib/python3.8/site-packages/gff3tool-2.1.0-py3.8.egg/gff3tool/lib/inter_model/inter_model.py", line 151, in main
    r = check_incorrectly_split_genes(gff, gff_file, fasta_file, logger)
  File "/public1/home/sc30852/anaconda3/envs/GFF_env/lib/python3.8/site-packages/gff3tool-2.1.0-py3.8.egg/gff3tool/lib/inter_model/inter_model.py", line 88, in check_incorrectly_split_genes
    subprocess.Popen([cmd, '-in', 'tmp_cds.fa', '-dbtype', 'nucl']).wait()
  File "/public1/home/sc30852/anaconda3/envs/GFF_env/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/public1/home/sc30852/anaconda3/envs/GFF_env/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/public1/home/sc30852/anaconda3/envs/GFF_env/lib/python3.8/site-packages/gff3tool-2.1.0-py3.8.egg/gff3tool/lib/ncbi-blast+/bin/makeblastdb'

It seems that makeblastdb (part of the NCBI BLAST+ suite) is required by gff3_QC, but it was not found in my environment. Could you please clarify if makeblastdb should be installed separately, or if there are additional installation steps to include it in the expected directory? I am currently using an Anaconda environment (GFF_env) for this project.

Thank you in advance for your help!

**Comment by MonicaPoelchau-USDA** [comment]
Sorry to hear you're having problems! Could you let me know how you installed the gff3toolkit, and what version of python you're using? Thanks!

**Comment by hj-99** [comment]
Thank you for getting back to me!

I installed the GFF3toolkit using the following command:

pip install git+https://github.com/NAL-i5K/GFF3toolkit.git

My Python version is 3.8.16. Additionally, I received an error indicating that a blast file could not be found.

**Comment by MonicaPoelchau-USDA** [comment]
I tried 2 fresh installs using python 3.8.16 - one using a python environment, and one with a miniconda environment. For both installations the program installed the blast binaries. So I'm not sure what's going on with your setup. I'd suggest setting up a fresh python or miniconda environment and attempting to install the gff3toolkit again. Sorry I can't help more!
