### ISSUE TITLE
KeyError: 'replace'

### ISSUE THREAD

**Issue by tiramisutes** [NAL-i5K/GFF3toolkit#75]
Dear,
I get follows error when use gff3_merge for two gff3 files.
```
INFO     ========== Merge the two gff files ==========
INFO     Sorting the WA gff by following the order of Scaffold number and coordinates...
INFO     Sorting and printing out...
INFO     Sorting the other gff by following the order of Scaffold number and coordinates...
INFO     Sorting and printing out...
INFO     Reading WA gff3 file...
INFO     Reading the other gff3 file...
INFO     Identifying types of replacement based on replace tag...
INFO     Replacing...
Traceback (most recent call last):
  File "/public/home/zpxu/miniconda2/bin/gff3_merge", line 11, in <module>
    load_entry_point('gff3tool==1.3.0', 'console_scripts', 'gff3_merge')()
  File "/public/home/zpxu/miniconda2/lib/python2.7/site-packages/gff3tool/bin/gff3_merge.py", line 230, in script_main
    main(args.gff_file1, args.gff_file2, args.fasta, report_fh, args.output_gff, args.all, args.auto_assignment, args.user_defined_file1, args.user_defined_file2, logger=logger_stderr)
  File "/public/home/zpxu/miniconda2/lib/python2.7/site-packages/gff3tool/bin/gff3_merge.py", line 85, in main
    gff3_merge.merge.main(autoReviseGff, gff_file2, output_gff, report, user_defined1, user_defined2, logger)
  File "/public/home/zpxu/miniconda2/lib/python2.7/site-packages/gff3tool/lib/gff3_merge/merge.py", line 145, in main
    ans = ReplaceGroups.replacer_multi(root, ReplaceGroups, gff3M, u1_types, u2_types)
  File "/public/home/zpxu/miniconda2/lib/python2.7/site-packages/gff3tool/lib/gff3_merge/../replace_OGS.py", line 874, in replacer_multi
    self.info.append('{0:s}\t{1:s}\t{2:s}\t{3:s}'.format(originalID, newtarget['attributes']['ID'], newtarget['attributes']['replace'], newtarget['attributes']['modified_track']))
KeyError: 'replace'
```

**Comment by mpoelchau** [comment]
Sorry about the problem! Did you run gff3_QC on the gff3 files before merging? 

If you send the command that you used and the input files, we can take a look into this for you.

**Comment by tiramisutes** [comment]
Yes, I have run `gff3_QC`,  `gff3_fix` and `gff3_sort` for two input files before merging. 
```
gff3_merge -g1 1corrected_sorted.gff3 -g2 2corrected_sorted.gff3 -f genome.fa.masked -og merged.gff -r merged_report.txt
```
But the input files is big.

**Comment by tiramisutes** [comment]
In the merging process, I get the files `other_sorted.gff` and `WA_sorted.gff` as follows. There as normal or have some mistake?
`other_sorted.gff`
```
##gff-version 3
sample1	AUGUSTUS	gene	417	1144	.	+	.	ID=g20854
sample1	AUGUSTUS	mRNA	417	1144	.	+	.	ID=g20854.t1;Parent=g20854
sample1	AUGUSTUS	CDS	417	533	0.5	+	1	ID=g20854.t1.CDS1;Parent=g20854.t1
sample1	AUGUSTUS	CDS	857	925	0.43	+	1	ID=g20854.t1.CDS2;Parent=g20854.t1
sample1	AUGUSTUS	CDS	1081	1144	0.39	+	1	ID=g20854.t1.CDS3;Parent=g20854.t1
sample1	AUGUSTUS	stop_codon	1142	1144	.	+	0	Parent=g20854.t1
###
sample1	AUGUSTUS	gene	5036	5335	.	-	.	ID=g20855
sample1	AUGUSTUS	mRNA	5036	5335	.	-	.	ID=g20855.t1;Parent=g20855
sample1	AUGUSTUS	CDS	5036	5335	1.0	-	0	ID=g20855.t1.CDS1;Parent=g20855.t1
sample1	AUGUSTUS	start_codon	5333	5335	.	-	0	Parent=g20855.t1
sample1	AUGUSTUS	stop_codon	5036	5038	.	-	0	Parent=g20855.t1
```
`WA_sorted.gff` 
```
##gff-version 3
sample1	AUGUSTUS	gene	5036	5335	.	-	.	ID=g18336
sample1	AUGUSTUS	mRNA	5036	5335	.	-	.	ID=g18336.t1;Parent=g18336;replace=g20855.t1
sample1	AUGUSTUS	CDS	5036	5335	0.97	-	0	ID=g18336.t1.CDS1;Parent=g18336.t1
sample1	AUGUSTUS	start_codon	5333	5335	.	-	0	Parent=g18336.t1
sample1	AUGUSTUS	stop_codon	5036	5038	.	-	0	Parent=g18336.t1
###
sample1	AUGUSTUS	gene	10842	11267	.	+	.	ID=g18337
sample1	AUGUSTUS	mRNA	10842	11267	.	+	.	ID=g18337.t1;Parent=g18337;replace=g20856.t1
sample1	AUGUSTUS	CDS	10842	11267	0.96	+	0	ID=g18337.t1.CDS1;Parent=g18337.t1
sample1	AUGUSTUS	start_codon	10842	10844	.	+	0	Parent=g18337.t1
sample1	AUGUSTUS	stop_codon	11265	11267	.	+	0	Parent=g18337.t1
```

**Comment by mpoelchau** [comment]
The files other_sorted.gff and WA_sorted.gff are temporary files that get written into the auto_replace_tag/tmp directory. The WA_sorted.gff file contains the auto-assigned replace tags that tell the program which models to remove. If the merge program completes, they should be removed - but since the program died before completing, they were retained. 

I ran the program with these 2 files and a dummy fasta file, and the program worked - so there  must be some other aspect of your input files that is causing the program to fail.

Did you receive my email with the ftp site information? If you're comfortable sharing the files with us, that would help the debugging process. Or you could send me the output report from gff3_QC. 

Thanks for your patience!

Monica

**Comment by mpoelchau** [comment]
Hi @tiramisutes - I'm going to go ahead and close this issue, since we can't fix it unless we have an example file. Feel free to re-open the issue if you need to, though!

**Comment by gjs889969** [comment]
解决了吗，请问是怎么解决的
